-- AlterTable
ALTER TABLE `Carrier` ADD COLUMN `avgSpeedKmPerDay` INTEGER NOT NULL DEFAULT 500,
    ADD COLUMN `basePrice` DECIMAL(12, 2) NOT NULL DEFAULT 20.00,
    ADD COLUMN `handlingDays` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `insuranceRate` DECIMAL(6, 4) NOT NULL DEFAULT 0.003,
    ADD COLUMN `pricePerKg` DECIMAL(12, 4) NOT NULL DEFAULT 0.80,
    ADD COLUMN `pricePerKm` DECIMAL(12, 4) NOT NULL DEFAULT 0.05;
