-- AlterTable
ALTER TABLE `AuditLog` MODIFY `action` ENUM('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'REGISTER', 'OAUTH_LOGIN', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_ROLE_CHANGED', 'CARRIER_DELETED', 'CLIENT_DELETED', 'FREIGHT_QUOTE_DELETED') NOT NULL;

-- AlterTable
ALTER TABLE `Carrier` ADD COLUMN `deletedAt` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `Client` ADD COLUMN `deletedAt` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `FreightQuote` ADD COLUMN `deletedAt` DATETIME(3) NULL;
