-- AlterTable
ALTER TABLE `AuditLog` MODIFY `action` ENUM('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'REGISTER', 'OAUTH_LOGIN', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_ROLE_CHANGED', 'CARRIER_DELETED', 'CLIENT_DELETED', 'FREIGHT_QUOTE_DELETED', 'EXTERNAL_WEBHOOK_RECEIVED') NOT NULL;

-- AlterTable
ALTER TABLE `Tenant` ADD COLUMN `webhookSecret` VARCHAR(191) NULL;
